/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.8 */

#ifndef PB_VCU_FLEET_V26_10SEC_FLEET_PB_H_INCLUDED
#define PB_VCU_FLEET_V26_10SEC_FLEET_PB_H_INCLUDED
#include "pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _vcu_fleet_fleet_10_sec {
    uint32_t car_id;
    uint32_t trip_id;
    int32_t timestamp;
    uint32_t latitude;
    uint32_t longitude;
    uint32_t soc;
    uint32_t hv_soc_calculated;
    uint32_t battery_temp;
    int32_t mcu_temp_1;
    uint32_t speed;
    uint32_t odometer;
    uint32_t ambient_temp;
    uint32_t pack_voltage;
    int32_t pack_current;
    uint32_t charging_indicator;
    uint32_t dte;
    uint32_t ac_status;
    uint32_t min_cell_temp;
    uint32_t max_cell_temp;
    uint32_t min_cell_voltage;
    uint32_t max_cell_voltage;
    uint32_t altitude;
    uint32_t direction;
    uint32_t soh;
    int32_t identifier;
} vcu_fleet_fleet_10_sec;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define vcu_fleet_fleet_10_sec_init_default      {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define vcu_fleet_fleet_10_sec_init_zero         {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define vcu_fleet_fleet_10_sec_car_id_tag        1
#define vcu_fleet_fleet_10_sec_trip_id_tag       2
#define vcu_fleet_fleet_10_sec_timestamp_tag     3
#define vcu_fleet_fleet_10_sec_latitude_tag      4
#define vcu_fleet_fleet_10_sec_longitude_tag     5
#define vcu_fleet_fleet_10_sec_soc_tag           6
#define vcu_fleet_fleet_10_sec_hv_soc_calculated_tag 7
#define vcu_fleet_fleet_10_sec_battery_temp_tag  8
#define vcu_fleet_fleet_10_sec_mcu_temp_1_tag    9
#define vcu_fleet_fleet_10_sec_speed_tag         10
#define vcu_fleet_fleet_10_sec_odometer_tag      11
#define vcu_fleet_fleet_10_sec_ambient_temp_tag  12
#define vcu_fleet_fleet_10_sec_pack_voltage_tag  13
#define vcu_fleet_fleet_10_sec_pack_current_tag  14
#define vcu_fleet_fleet_10_sec_charging_indicator_tag 15
#define vcu_fleet_fleet_10_sec_dte_tag           16
#define vcu_fleet_fleet_10_sec_ac_status_tag     17
#define vcu_fleet_fleet_10_sec_min_cell_temp_tag 18
#define vcu_fleet_fleet_10_sec_max_cell_temp_tag 19
#define vcu_fleet_fleet_10_sec_min_cell_voltage_tag 20
#define vcu_fleet_fleet_10_sec_max_cell_voltage_tag 21
#define vcu_fleet_fleet_10_sec_altitude_tag      22
#define vcu_fleet_fleet_10_sec_direction_tag     23
#define vcu_fleet_fleet_10_sec_soh_tag           24
#define vcu_fleet_fleet_10_sec_identifier_tag    25

/* Struct field encoding specification for nanopb */
#define vcu_fleet_fleet_10_sec_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   car_id,            1) \
X(a, STATIC,   SINGULAR, UINT32,   trip_id,           2) \
X(a, STATIC,   SINGULAR, INT32,    timestamp,         3) \
X(a, STATIC,   SINGULAR, UINT32,   latitude,          4) \
X(a, STATIC,   SINGULAR, UINT32,   longitude,         5) \
X(a, STATIC,   SINGULAR, UINT32,   soc,               6) \
X(a, STATIC,   SINGULAR, UINT32,   hv_soc_calculated,   7) \
X(a, STATIC,   SINGULAR, UINT32,   battery_temp,      8) \
X(a, STATIC,   SINGULAR, INT32,    mcu_temp_1,        9) \
X(a, STATIC,   SINGULAR, UINT32,   speed,            10) \
X(a, STATIC,   SINGULAR, UINT32,   odometer,         11) \
X(a, STATIC,   SINGULAR, UINT32,   ambient_temp,     12) \
X(a, STATIC,   SINGULAR, UINT32,   pack_voltage,     13) \
X(a, STATIC,   SINGULAR, INT32,    pack_current,     14) \
X(a, STATIC,   SINGULAR, UINT32,   charging_indicator,  15) \
X(a, STATIC,   SINGULAR, UINT32,   dte,              16) \
X(a, STATIC,   SINGULAR, UINT32,   ac_status,        17) \
X(a, STATIC,   SINGULAR, UINT32,   min_cell_temp,    18) \
X(a, STATIC,   SINGULAR, UINT32,   max_cell_temp,    19) \
X(a, STATIC,   SINGULAR, UINT32,   min_cell_voltage,  20) \
X(a, STATIC,   SINGULAR, UINT32,   max_cell_voltage,  21) \
X(a, STATIC,   SINGULAR, UINT32,   altitude,         22) \
X(a, STATIC,   SINGULAR, UINT32,   direction,        23) \
X(a, STATIC,   SINGULAR, UINT32,   soh,              24) \
X(a, STATIC,   SINGULAR, INT32,    identifier,       25)
#define vcu_fleet_fleet_10_sec_CALLBACK NULL
#define vcu_fleet_fleet_10_sec_DEFAULT NULL

extern const pb_msgdesc_t vcu_fleet_fleet_10_sec_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define vcu_fleet_fleet_10_sec_fields &vcu_fleet_fleet_10_sec_msg

/* Maximum encoded size of messages (where known) */
#define VCU_FLEET_V26_10SEC_FLEET_PB_H_MAX_SIZE  vcu_fleet_fleet_10_sec_size
#define vcu_fleet_fleet_10_sec_size              180

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
