/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8 */

#include "V26_10sec_fleet.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(vcu_fleet_fleet_10_sec, vcu_fleet_fleet_10_sec, AUTO)



